# Black Box 5 Memory Schema
version: 5.0.0

# Directory Structure Rules
directories:
  - path: memory/plans
    description: "Active implementation plans and checklists"
    required: true
    auto_create: true
  
  - path: memory/context
    description: "Project-specific context and architecture decisions"
    required: true
    auto_create: true
    
  - path: scratch
    description: "Temporary working state (gitignored)"
    required: true
    auto_create: true

# Required Files (The 'FAT Table')
files:
  - path: memory/code_index.md
    description: "Map of all source code files"
    generator: "indexer.py"
    required: true
  
  - path: config.yml
    description: "Project configuration map"
    required: true

# Formatting Standards
standards:
  plans: "markdown"
  context: "markdown"
  index: "markdown_list"
