#!/bin/bash
#
# Generate README.md files for all directories in .blackbox4
# Ensures every folder has proper documentation
#

BB4_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# Counters
total=0
created=0
skipped=0

log_info "Scanning .blackbox4 for missing README.md files..."
echo

# Find all directories and process them
while IFS= read -r -d '' dir; do
    ((total++))

    rel_path="${dir#$BB4_ROOT/}"
    dir_name="$(basename "$dir")"

    # Skip if README already exists
    if [[ -f "$dir/README.md" ]]; then
        ((skipped++))
        continue
    fi

    # Create generic README
    cat > "$dir/README.md" << EOF
# ${dir_name}

Component in Blackbox4.

## Location

\`\`\`
${rel_path}
\`\`\`

## Purpose

This directory contains: \`${dir_name}\`

## Usage

See parent directory documentation for more information.

---

*This README was auto-generated by \`generate-readmes.sh\`*
EOF

    ((created++))
    log_success "Created: $rel_path/README.md"

done < <(find "$BB4_ROOT" -mindepth 1 -type d -print0 | sort -z)

echo
log_info "README.md generation complete!"
echo
echo "Summary:"
echo "  Total directories scanned: $total"
echo "  README.md files created: $created"
echo "  Already had README.md: $skipped"
echo

if [[ $created -gt 0 ]]; then
    log_success "Successfully created $created README.md files"
fi

if [[ $skipped -gt 0 ]]; then
    log_info "$skipped directories already had README.md files"
fi
