#!/usr/bin/env python3
import os
from pathlib import Path

def generate_index(root_dir=".", output_file="memory/code_index.md"):
    print(f"🔍 Indexing codebase from {root_dir}...")
    
    src_path = Path(root_dir) / "src"
    if not src_path.exists():
        print("❌ 'src' directory not found.")
        return

    index_lines = ["# Codebase Index", "", "This file is auto-generated by Black Box 5.", ""]
    
    count = 0
    for root, dirs, files in os.walk(src_path):
        # Filter hidden dirs
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        
        for file in files:
            if file.startswith('.') or file.endswith(('.png', '.jpg', '.ico', '.json')):
                continue
                
            full_path = Path(root) / file
            rel_path = full_path.relative_to(root_dir)
            index_lines.append(f"- [{file}]({rel_path})")
            count += 1
            
    output_path = Path(root_dir) / output_file
    with open(output_path, "w") as f:
        f.write("\n".join(index_lines))
        
    print(f"✅ Indexed {count} files to {output_file}")

if __name__ == "__main__":
    generate_index()
