# <!-- Powered by BMAD™ Core -->
# CLIENT PORTAL CONFIGURATION - Enhanced for client-facing features
markdownExploder: true
qa:
  qaLocation: docs/qa
  clientSecurityReviews: true
  wcagComplianceChecks: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
  clientJourneyMappingRequired: true
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
  clientPortalArchitecture: true
customTechnicalDocuments: 
  - docs/client-security-requirements.md
  - docs/client-accessibility-standards.md
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
  - docs/client-portal-patterns.md
  - .bmad-core/knowledge-base/pdr-cookbook-context.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: ClientBMad
clientPortal:
  performanceRequirements:
    firstContentfulPaint: "< 1.2s"
    largestContentfulPaint: "< 2.0s"
    mobileFirstDesign: true
  security:
    dataIsolation: mandatory
    auditLogging: enabled
    multiFactorAuth: required
  accessibility:
    wcagLevel: "AA"
    complianceChecking: automated
  testing:
    crossDeviceTesting: required
    clientJourneyTesting: mandatory
